using DevExpress.Export;
using DevExpress.Utils;
using DevExpress.XtraBars;
using DevExpress.XtraCharts;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraPrinting;
using dto;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using static System.Windows.Forms.Design.AxImporter;
using DevExpress.XtraGrid.Export;
using bll;
using DevExpress.XtraCharts.Native;

namespace hehe
{
    public partial class ThongKeDoanhThu : Form
    {
        public ThongKeDoanhThu()
        {
            InitializeComponent();
           
        }
        private void btn_chinhsuacv_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
         
          

        }
        void loadCBNam()
        {
           
            cbb_Nam.Properties.Items.Clear();
            for (int i = 2000; i<= 2050;i++)
            {
                cbb_Nam.Properties.Items.Add("Năm " + i.ToString());

                //// Thêm BarButtonItem vào RibbonPageGroup
                //BarButtonItem barButtonItem1 = new BarButtonItem();
                //barButtonItem1.Caption = "Tháng " + i.ToString();
                //barButtonItem1.Name = i.ToString();
                //barButtonItem1.ItemClick += BarButtonItem2_ItemClick;
                //this.DT.ItemLinks.Add(barButtonItem1);
            }
        }
        void loadCBThang()
        {
            cbb_Thang.Properties.Items.Clear();
            for (int i = 1; i <= 12; i++)
            {
                cbb_Thang.Properties.Items.Add("Tháng " + i.ToString());

                //// Thêm BarButtonItem vào RibbonPageGroup
                //BarButtonItem barButtonItem1 = new BarButtonItem();
                //barButtonItem1.Caption = "Tháng " + i.ToString();
                //barButtonItem1.Name = i.ToString();
                //barButtonItem1.ItemClick += BarButtonItem2_ItemClick;
                //this.DT.ItemLinks.Add(barButtonItem1);
            }
        }
        Sach_DonHang_bll s_dh_bll = new Sach_DonHang_bll();
        void loadTHongKe()
        {
           
            List<Sach_DonHang_dto> ds = s_dh_bll.ThongKe();
            //ChartTitle title = new ChartTitle();
            //title.Text = "Doanh thu theo các tháng qua từng năm";
           
         
            chartControl1.DataSource = ds;
            //// The Year property's unique values determine series.
            //chartControl1.SeriesTemplate.SeriesDataMember = "Nam";
            //// These properties define data members that
            //// the chart uses to create series points.
            //chartControl1.SeriesTemplate.ArgumentDataMember = "Thang";
            //chartControl1.SeriesTemplate.ValueDataMembers.AddRange("TongTien");
 
        }
        void loadPie()
        {
            //Series series = new Series("Nam", ViewType.Bar);
            //chartControl2.Series.Add(series);
            chartControl2.Titles[0].Text = "PHẦN TRĂM CÁC THÁNG CỦA NĂM " + cbb_Nam.EditValue.ToString().Substring(4);
            chartControl2.DataSource = s_dh_bll.ThongKe().Where(t => t.Nam == int.Parse(cbb_Nam.EditValue.ToString().Substring(4)));
            //// The Year property's unique values determine series.
            //chartControl2.SeriesTemplate.SeriesDataMember = "Nam";
            //// These properties define data members that
            //// the chart uses to create series points.
            //chartControl2.SeriesTemplate.ArgumentDataMember = "Thang";
            //chartControl2.SeriesTemplate.ValueDataMembers.AddRange("TongTien");
        }
        private void BarButtonItem2_ItemClick(object sender, ItemClickEventArgs e)
        {
            Chart_thongke.thang = decimal.Parse(e.Item.Name);
            Chart_thongke f = new Chart_thongke();
            f.Show();
        }

        private void ThongKeDoanhThu_Load(object sender, EventArgs e)
        {
            loadCBNam();
            loadCBThang();
            cbb_Nam.EditValue = "Năm " +  DateTime.Now.Year;
            cbb_Thang.EditValue = "Tháng " + DateTime.Now.Month;
            loadTHongKe();
            loadPie();
            loadDS();
        }
        void loadDS()
        {
            int nam = int.Parse(cbb_Nam.EditValue.ToString().Substring(4));
            int thang = int.Parse(cbb_Thang.EditValue.ToString().Substring(6));
            gc_dh.DataSource= s_dh_bll.select().Where(t => t.Nam == nam && t.Thang == thang);
        }
        private void btn_TaiLai_ItemClick(object sender, ItemClickEventArgs e)
        {
            // This line of code is generated by Data Source Configuration Wizard
            loadCBThang();
            loadTHongKe();
            loadPie();
            loadDS();
        }
       

        private void btn_Export_ItemClick(object sender, ItemClickEventArgs e)
        {
            Utils.ExportToExcel( "D:\\ThongKeDoanhThu.xlsx", gridView1);
        }
        private void PrintGridView(GridView gridView)
        {
            gridView.ShowPrintPreview();
        }
        private void In_ItemClick(object sender, ItemClickEventArgs e)
        {

            PrintGridView(gridView1);
        }

        private void dONHANG1GridControl_Click(object sender, EventArgs e)
        {
            
        }

        private void cbb_Thoigian_SelectedIndexChanged(object sender, EventArgs e)
        {
            loadPie();
            loadDS();
        }

        private void cbb_Thang_EditValueChanged(object sender, EventArgs e)
        {
            loadDS();
        }
    }
}
